"""create initial schema

Revision ID: 00f31c245a1a
Revises: 
Create Date: 2026-04-21 20:32:46.119190
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '00f31c245a1a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arac',
    sa.Column('plaka', sa.String(length=20), nullable=False),
    sa.Column('tip', sa.String(length=100), nullable=False),
    sa.Column('kapasite_kg', sa.Integer(), nullable=False),
    sa.Column('durum', sa.Enum('AKTIF', 'PASIF', 'BAKIMDA', name='arac_durumu_enum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_arac'))
    )
    op.create_index(op.f('ix_arac_plaka'), 'arac', ['plaka'], unique=True)
    op.create_table('bolge',
    sa.Column('ad', sa.String(length=150), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bolge'))
    )
    op.create_index(op.f('ix_bolge_ad'), 'bolge', ['ad'], unique=True)
    op.create_table('ihbar',
    sa.Column('aciklama', sa.Text(), nullable=False),
    sa.Column('enlem', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('boylam', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('fotograf_url', sa.String(length=500), nullable=True),
    sa.Column('durum', sa.Enum('BEKLIYOR', 'GOREVE_ATANDI', 'ISLEMDE', 'COZULDU', 'GECERSIZ', name='ihbar_durumu_enum'), nullable=False),
    sa.Column('olusturma_tarihi', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ihbar'))
    )
    op.create_table('rol',
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rol'))
    )
    op.create_index(op.f('ix_rol_ad'), 'rol', ['ad'], unique=True)
    op.create_table('sistemparametresi',
    sa.Column('anahtar', sa.String(length=150), nullable=False),
    sa.Column('deger', sa.String(length=500), nullable=False),
    sa.Column('veri_tipi', sa.String(length=50), nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sistemparametresi'))
    )
    op.create_index(op.f('ix_sistemparametresi_anahtar'), 'sistemparametresi', ['anahtar'], unique=True)
    op.create_table('stok',
    sa.Column('atik_tipi', sa.Enum('PLASTIK', 'CAM', 'METAL', 'KAGIT', 'ORGANIK', 'DIGER', name='atik_tipi_enum'), nullable=False),
    sa.Column('toplam_miktar_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stok')),
    sa.UniqueConstraint('atik_tipi', name=op.f('uq_stok_atik_tipi'))
    )
    op.create_table('konteyner',
    sa.Column('kod', sa.String(length=100), nullable=False),
    sa.Column('enlem', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('boylam', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('doluluk_orani', sa.Integer(), nullable=False),
    sa.Column('durum', sa.Enum('NORMAL', 'IZLENIYOR', 'KRITIK', 'GOREVE_ATANDI', 'BOSALTILDI', name='konteyner_durumu_enum'), nullable=False),
    sa.Column('bolge_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('doluluk_orani >= 0 AND doluluk_orani <= 100', name=op.f('ck_konteyner_doluluk_orani_range')),
    sa.ForeignKeyConstraint(['bolge_id'], ['bolge.id'], name=op.f('fk_konteyner_bolge_id_bolge'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_konteyner'))
    )
    op.create_index(op.f('ix_konteyner_bolge_id'), 'konteyner', ['bolge_id'], unique=False)
    op.create_index(op.f('ix_konteyner_kod'), 'konteyner', ['kod'], unique=True)
    op.create_table('personel',
    sa.Column('tc_no', sa.String(length=11), nullable=False),
    sa.Column('sifre_hash', sa.String(length=255), nullable=False),
    sa.Column('ad_soyad', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefon', sa.String(length=30), nullable=True),
    sa.Column('taban_maas', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cocuk_sayisi', sa.Integer(), nullable=False),
    sa.Column('aktif_mi', sa.Boolean(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], name=op.f('fk_personel_rol_id_rol'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personel'))
    )
    op.create_index(op.f('ix_personel_ad_soyad'), 'personel', ['ad_soyad'], unique=False)
    op.create_index(op.f('ix_personel_email'), 'personel', ['email'], unique=True)
    op.create_index(op.f('ix_personel_rol_id'), 'personel', ['rol_id'], unique=False)
    op.create_index(op.f('ix_personel_tc_no'), 'personel', ['tc_no'], unique=True)
    op.create_table('satis',
    sa.Column('tarih', sa.DateTime(timezone=True), nullable=False),
    sa.Column('miktar_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('birim_fiyat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('toplam_tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('durum', sa.Enum('BEKLEMEDE', 'ONAYLANDI', 'REDDEDILDI', name='satis_onay_durumu_enum'), nullable=False),
    sa.Column('stok_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stok_id'], ['stok.id'], name=op.f('fk_satis_stok_id_stok'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_satis'))
    )
    op.create_index(op.f('ix_satis_stok_id'), 'satis', ['stok_id'], unique=False)
    op.create_table('bakimkaydi',
    sa.Column('tarih', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=False),
    sa.Column('maliyet_tl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('durum', sa.Enum('ACILDI', 'INCELEMEDE', 'TAMAMLANDI', 'IPTAL', name='bakim_durumu_enum'), nullable=False),
    sa.Column('teknik_tamamlanma_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arac_id', sa.Integer(), nullable=False),
    sa.Column('olusturan_personel_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['arac_id'], ['arac.id'], name=op.f('fk_bakimkaydi_arac_id_arac'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['olusturan_personel_id'], ['personel.id'], name=op.f('fk_bakimkaydi_olusturan_personel_id_personel'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bakimkaydi'))
    )
    op.create_index(op.f('ix_bakimkaydi_arac_id'), 'bakimkaydi', ['arac_id'], unique=False)
    op.create_index(op.f('ix_bakimkaydi_olusturan_personel_id'), 'bakimkaydi', ['olusturan_personel_id'], unique=False)
    op.create_table('gelirkaydi',
    sa.Column('tarih', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=False),
    sa.Column('durum', sa.Enum('BEKLEMEDE', 'ONAYLANDI', 'REDDEDILDI', name='gelir_onay_durumu_enum'), nullable=False),
    sa.Column('satis_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['satis_id'], ['satis.id'], name=op.f('fk_gelirkaydi_satis_id_satis'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gelirkaydi')),
    sa.UniqueConstraint('satis_id', name=op.f('uq_gelirkaydi_satis_id'))
    )
    op.create_table('gorev',
    sa.Column('tip', sa.Enum('IHBAR', 'KRITIK_KONTEYNER', name='gorev_tipi_enum'), nullable=False),
    sa.Column('oncelik', sa.Integer(), nullable=False),
    sa.Column('durum', sa.Enum('BEKLIYOR', 'ATANDI', 'ISLEMDE', 'TAMAMLANDI', 'BASARISIZ', name='gorev_durumu_enum'), nullable=False),
    sa.Column('sonuc', sa.Enum('TAMAMLANDI', 'ULASILAMADI', 'YANLIS_IHBAR', 'TEKRAR_KONTROL_GEREKLI', name='gorev_sonucu_enum'), nullable=True),
    sa.Column('planlanan_tarih', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tamamlanma_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sira_no', sa.Integer(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('ihbar_id', sa.Integer(), nullable=True),
    sa.Column('konteyner_id', sa.Integer(), nullable=True),
    sa.Column('atanan_sofor_id', sa.Integer(), nullable=True),
    sa.Column('kullanilan_arac_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(ihbar_id IS NOT NULL AND konteyner_id IS NULL) OR (ihbar_id IS NULL AND konteyner_id IS NOT NULL)', name=op.f('ck_gorev_gorev_tek_kaynak')),
    sa.ForeignKeyConstraint(['atanan_sofor_id'], ['personel.id'], name=op.f('fk_gorev_atanan_sofor_id_personel'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ihbar_id'], ['ihbar.id'], name=op.f('fk_gorev_ihbar_id_ihbar'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['konteyner_id'], ['konteyner.id'], name=op.f('fk_gorev_konteyner_id_konteyner'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kullanilan_arac_id'], ['arac.id'], name=op.f('fk_gorev_kullanilan_arac_id_arac'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gorev'))
    )
    op.create_index(op.f('ix_gorev_atanan_sofor_id'), 'gorev', ['atanan_sofor_id'], unique=False)
    op.create_index(op.f('ix_gorev_ihbar_id'), 'gorev', ['ihbar_id'], unique=False)
    op.create_index(op.f('ix_gorev_konteyner_id'), 'gorev', ['konteyner_id'], unique=False)
    op.create_index('ix_gorev_kritik_konteyner_acik', 'gorev', ['konteyner_id', 'durum'], unique=False)
    op.create_index(op.f('ix_gorev_kullanilan_arac_id'), 'gorev', ['kullanilan_arac_id'], unique=False)
    op.create_table('islemlog',
    sa.Column('islem_tarihi', sa.DateTime(timezone=True), nullable=False),
    sa.Column('islem_tipi', sa.String(length=120), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=False),
    sa.Column('varlik_tipi', sa.String(length=120), nullable=False),
    sa.Column('varlik_id', sa.Integer(), nullable=True),
    sa.Column('islemi_yapan_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['islemi_yapan_id'], ['personel.id'], name=op.f('fk_islemlog_islemi_yapan_id_personel'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_islemlog'))
    )
    op.create_index(op.f('ix_islemlog_islem_tipi'), 'islemlog', ['islem_tipi'], unique=False)
    op.create_index(op.f('ix_islemlog_islemi_yapan_id'), 'islemlog', ['islemi_yapan_id'], unique=False)
    op.create_index(op.f('ix_islemlog_varlik_tipi'), 'islemlog', ['varlik_tipi'], unique=False)
    op.create_table('maasodeme',
    sa.Column('donem_ay', sa.Integer(), nullable=False),
    sa.Column('donem_yil', sa.Integer(), nullable=False),
    sa.Column('odeme_tarihi', sa.Date(), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('odeme_tipi', sa.Enum('AVANS', 'TEKLI', 'TOPLU', name='odeme_tipi_enum'), nullable=False),
    sa.Column('durum', sa.Enum('BEKLIYOR', 'ODENDI', 'IPTAL', name='odeme_durumu_enum'), nullable=False),
    sa.Column('personel_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['personel_id'], ['personel.id'], name=op.f('fk_maasodeme_personel_id_personel'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maasodeme')),
    sa.UniqueConstraint('personel_id', 'donem_ay', 'donem_yil', 'odeme_tipi', name='uq_maasodeme_donem_tip')
    )
    op.create_index(op.f('ix_maasodeme_personel_id'), 'maasodeme', ['personel_id'], unique=False)
    op.create_table('tesisteslim',
    sa.Column('tarih', sa.DateTime(timezone=True), nullable=False),
    sa.Column('toplam_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('onaylandi_mi', sa.Boolean(), nullable=False),
    sa.Column('onay_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('teslim_eden_sofor_id', sa.Integer(), nullable=False),
    sa.Column('teslim_alan_operator_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teslim_alan_operator_id'], ['personel.id'], name=op.f('fk_tesisteslim_teslim_alan_operator_id_personel'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teslim_eden_sofor_id'], ['personel.id'], name=op.f('fk_tesisteslim_teslim_eden_sofor_id_personel'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tesisteslim'))
    )
    op.create_index(op.f('ix_tesisteslim_teslim_alan_operator_id'), 'tesisteslim', ['teslim_alan_operator_id'], unique=False)
    op.create_index(op.f('ix_tesisteslim_teslim_eden_sofor_id'), 'tesisteslim', ['teslim_eden_sofor_id'], unique=False)
    op.create_table('giderkaydi',
    sa.Column('tarih', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=False),
    sa.Column('durum', sa.Enum('BEKLEMEDE', 'ONAYLANDI', 'REDDEDILDI', name='onay_durumu_enum'), nullable=False),
    sa.Column('bakim_kaydi_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bakim_kaydi_id'], ['bakimkaydi.id'], name=op.f('fk_giderkaydi_bakim_kaydi_id_bakimkaydi'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_giderkaydi')),
    sa.UniqueConstraint('bakim_kaydi_id', name=op.f('uq_giderkaydi_bakim_kaydi_id'))
    )
    op.create_table('stokhareketi',
    sa.Column('tarih', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atik_tipi', sa.Enum('PLASTIK', 'CAM', 'METAL', 'KAGIT', 'ORGANIK', 'DIGER', name='stok_hareketi_atik_tipi_enum'), nullable=False),
    sa.Column('miktar_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('tesis_teslim_id', sa.Integer(), nullable=False),
    sa.Column('stok_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stok_id'], ['stok.id'], name=op.f('fk_stokhareketi_stok_id_stok'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tesis_teslim_id'], ['tesisteslim.id'], name=op.f('fk_stokhareketi_tesis_teslim_id_tesisteslim'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stokhareketi'))
    )
    op.create_index(op.f('ix_stokhareketi_stok_id'), 'stokhareketi', ['stok_id'], unique=False)
    op.create_index(op.f('ix_stokhareketi_tesis_teslim_id'), 'stokhareketi', ['tesis_teslim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stokhareketi_tesis_teslim_id'), table_name='stokhareketi')
    op.drop_index(op.f('ix_stokhareketi_stok_id'), table_name='stokhareketi')
    op.drop_table('stokhareketi')
    op.drop_table('giderkaydi')
    op.drop_index(op.f('ix_tesisteslim_teslim_eden_sofor_id'), table_name='tesisteslim')
    op.drop_index(op.f('ix_tesisteslim_teslim_alan_operator_id'), table_name='tesisteslim')
    op.drop_table('tesisteslim')
    op.drop_index(op.f('ix_maasodeme_personel_id'), table_name='maasodeme')
    op.drop_table('maasodeme')
    op.drop_index(op.f('ix_islemlog_varlik_tipi'), table_name='islemlog')
    op.drop_index(op.f('ix_islemlog_islemi_yapan_id'), table_name='islemlog')
    op.drop_index(op.f('ix_islemlog_islem_tipi'), table_name='islemlog')
    op.drop_table('islemlog')
    op.drop_index(op.f('ix_gorev_kullanilan_arac_id'), table_name='gorev')
    op.drop_index('ix_gorev_kritik_konteyner_acik', table_name='gorev')
    op.drop_index(op.f('ix_gorev_konteyner_id'), table_name='gorev')
    op.drop_index(op.f('ix_gorev_ihbar_id'), table_name='gorev')
    op.drop_index(op.f('ix_gorev_atanan_sofor_id'), table_name='gorev')
    op.drop_table('gorev')
    op.drop_table('gelirkaydi')
    op.drop_index(op.f('ix_bakimkaydi_olusturan_personel_id'), table_name='bakimkaydi')
    op.drop_index(op.f('ix_bakimkaydi_arac_id'), table_name='bakimkaydi')
    op.drop_table('bakimkaydi')
    op.drop_index(op.f('ix_satis_stok_id'), table_name='satis')
    op.drop_table('satis')
    op.drop_index(op.f('ix_personel_tc_no'), table_name='personel')
    op.drop_index(op.f('ix_personel_rol_id'), table_name='personel')
    op.drop_index(op.f('ix_personel_email'), table_name='personel')
    op.drop_index(op.f('ix_personel_ad_soyad'), table_name='personel')
    op.drop_table('personel')
    op.drop_index(op.f('ix_konteyner_kod'), table_name='konteyner')
    op.drop_index(op.f('ix_konteyner_bolge_id'), table_name='konteyner')
    op.drop_table('konteyner')
    op.drop_table('stok')
    op.drop_index(op.f('ix_sistemparametresi_anahtar'), table_name='sistemparametresi')
    op.drop_table('sistemparametresi')
    op.drop_index(op.f('ix_rol_ad'), table_name='rol')
    op.drop_table('rol')
    op.drop_table('ihbar')
    op.drop_index(op.f('ix_bolge_ad'), table_name='bolge')
    op.drop_table('bolge')
    op.drop_index(op.f('ix_arac_plaka'), table_name='arac')
    op.drop_table('arac')
    # ### end Alembic commands ###

